### ISSUE TITLE
Latest libkdumpfile failed to open Xen kdump file

### ISSUE THREAD

**Issue by firogh** [ptesarik/libkdumpfile#23]
l3mule:/space/dumps/ziu/SR101243410381> crash-python  -d  ./modules.debug -D vmlinux.debug  vmlinux.gz SR_101243410381_lpinstiaas01.core
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/kdump/target.py", line 89, in xfer_partial
    r = self.kdump.read(KDUMP_KVADDR, offset, ln)
kdumpfile.exceptions.NoDataException: Page not found
crash-python: Error in Python while executing xfer_partial callback., exiting
Traceback (most recent call last):
  File "<string>", line 36, in <module>
  File "/usr/lib/python3.6/site-packages/crash/kernel.py", line 146, in __init__
    self.version = self.extract_version()
  File "/usr/lib/python3.6/site-packages/crash/kernel.py", line 352, in extract_version
    banner = self._get_minsymbol_as_string('linux_banner')
  File "/usr/lib/python3.6/site-packages/crash/kernel.py", line 334, in _get_minsymbol_as_string
    return val.address.cast(self.types.char_p_type).string()
gdb.error: Error in Python while executing xfer_partial callback.

**Comment by ptesarik** [comment]
I wonder if this failure could be related to commit 464e9cd. Unfortunately, the dump is gone now. Do you happen to have any other dumps that trigger the bug?

**Comment by ptesarik** [comment]
After more than a year, it does not seem like we could move this forward. Let's assume the original bug is indeed fixed with commit 464e9cd.
